name: cli-tests
on: push

jobs:
  tests:
    name: 'Run Repo Tests'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "Setup node Version"
        uses: actions/setup-node@v2
        with:
          node-version: "12"

      - name: "Cache Dependencies"
      - uses: bahmutov/npm-install@v1
        with:
          install-command: yarn --frozen-lockfile --silent

      - name: "Run Repo Format"
        id: run-repo-format
        run: yarn format

      - name: "Run Repo Tests"
        id: run-repo-tests
        run: yarn test
